# Generated by Django 4.1.7 on 2023-03-11 12:34

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=catalog.models.Product.image_upload_to),
        ),
    ]
